import Head from 'next/head'
import Hero from '@/components/Hero'
import Shop from '@/pages/shop'
import Contact from '@/components/Contact'

export default function Home() {

  return (
    <>
      <Head>
        <title>NFTPlace - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
      <main className='bg-white dark:bg-gray-900'>
        <div className="hero">
          <Hero />
        </div>
        <div className='shop'>
          <Shop />
        </div>
        <div className="contact">
          <Contact />
        </div>
      </main>
    </>
  )
}
